#
# Copyright(C) Advanced Micro Devices, Inc. All rights reserved.
#
# You may not use this software and documentation (if any) (collectively,
# the "Materials") except in compliance with the terms and conditions of
# the Software License Agreement included with the Materials or otherwise as
# set forth in writing and signed by you and an authorized signatory of AMD.
# If you do not have a copy of the Software License Agreement, contact your
# AMD representative for a copy.
#
# You agree that you will not reverse engineer or decompile the Materials,
# in whole or in part, except as allowed by applicable law.
#
# THE MATERIALS ARE DISTRIBUTED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OR
# REPRESENTATIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.

CC                    := gcc
CXX                   := g++

# cmake >= 4.0 requires an explicit minimum policy version for projects that
# set cmake_minimum_required < 3.5 (grpc, abseil).  Detect and pass it.
CMAKE_MAJOR := $(shell cmake --version 2>/dev/null | awk 'NR==1{split($$3,v,"."); print v[1]}')
CMAKE_POLICY_FLAG := $(if $(filter 4 5 6 7 8 9,$(CMAKE_MAJOR)),-DCMAKE_POLICY_VERSION_MINIMUM=3.5,)

# libs serial across each other: each recipe already runs make -j$(nproc)
# internally; concurrent libs = Nlibs x nproc oversubscribe -> OOM grpc/boost.
.NOTPARALLEL:

# Third-party build targets
.PHONY: third-party-libs protobuf-build abseil-build grpc-build zeromq-build libev-build boost-build

third-party-libs: protobuf-build abseil-build grpc-build zeromq-build libev-build boost-build

protobuf-build:
	@echo "Building protobuf..."
	cd $(PROTOBUF_DIR) && \
	./autogen.sh && \
	./configure --prefix=$(BLD_DIR) && \
	make -j$(shell nproc) && \
	make install

abseil-build:
	@echo "Building abseil-cpp..."
	cd $(ABSEIL_DIR) && \
	mkdir -p cmake/build && \
	cd cmake/build && \
	cmake -DCMAKE_INSTALL_PREFIX=$(BLD_DIR) \
		$(CMAKE_POLICY_FLAG) \
		../../ && \
	make -j$(shell nproc) && \
	make install

grpc-build: protobuf-build abseil-build
	@echo "Building gRPC..."
	cd $(GRPC_DIR) && \
	mkdir -p cmake/build && \
	cd cmake/build && \
	cmake -DgRPC_INSTALL=ON \
		-DgRPC_BUILD_TESTS=OFF \
		-DCMAKE_INSTALL_PREFIX=$(BLD_DIR) \
		$(CMAKE_POLICY_FLAG) \
		../../ && \
	make -j$(shell nproc) && \
	make install && \
	mkdir -p $(BLD_BIN_DIR) && \
	cp -vf grpc_cpp_plugin $(BLD_BIN_DIR)/grpc_cpp_plugin && \
	cp -vf grpc_python_plugin $(BLD_BIN_DIR)/grpc_python_plugin && \
	rm -rf $(BLD_DIR)/lib/cmake && \
	rm -rf $(GRPC_DIR)/cmake/build

zeromq-build:
	@echo "Building ZeroMQ..."
	cd $(ZEROMQ_DIR) && \
	./autogen.sh && \
	./configure --prefix=$(BLD_DIR) CXXFLAGS="-Wno-error=address" && \
	make -j$(shell nproc) && \
	make install

libev-build:
	@echo "Building libev..."
	cd $(LIBEV_DIR) && \
	./configure --prefix=$(BLD_DIR) && \
	make -j$(shell nproc) && \
	make install

boost-build:
	@echo "Building Boost..."
	cd $(BOOST_DIR) && \
	./bootstrap.sh --prefix=$(BLD_DIR) && \
	./b2 install && \
	rm -rf $(BLD_DIR)/share

